"""
AEGIS-X API Repository Base Protocols & Interfaces.

Defines persistence contracts for models, datasets, analyses, and advanced reliability capabilities.
Both SQLite and Supabase implementations adhere strictly to these interfaces.
"""

from typing import List, Optional, Protocol, runtime_checkable

from api.db.models import (
    AnalysisRecord,
    DatasetRecord,
    FailureMemoryRecord,
    FaultTestRecord,
    ModelRecord,
    PredictionRecord,
    ReferenceStateRecord,
    StressTestRecord,
    WarningRecord,
)


@runtime_checkable
class IModelRepository(Protocol):
    def create(self, record: ModelRecord) -> ModelRecord: ...
    def get_by_id(self, model_id: str, owner_id: Optional[str] = None) -> Optional[ModelRecord]: ...
    def list_all(self, owner_id: Optional[str] = None) -> List[ModelRecord]: ...


@runtime_checkable
class IDatasetRepository(Protocol):
    def create(self, record: DatasetRecord) -> DatasetRecord: ...
    def get_by_id(self, dataset_id: str, owner_id: Optional[str] = None) -> Optional[DatasetRecord]: ...
    def list_by_model(self, model_id: Optional[str] = None, owner_id: Optional[str] = None) -> List[DatasetRecord]: ...
    def delete(self, dataset_id: str, owner_id: Optional[str] = None) -> bool: ...


@runtime_checkable
class IReferenceStateRepository(Protocol):
    def save_or_update(self, record: ReferenceStateRecord) -> ReferenceStateRecord: ...
    def get_by_model_id(self, model_id: str, owner_id: Optional[str] = None) -> Optional[ReferenceStateRecord]: ...


@runtime_checkable
class IAnalysisRepository(Protocol):
    def create(self, record: AnalysisRecord) -> AnalysisRecord: ...
    def get_by_id(self, analysis_id: str, owner_id: Optional[str] = None) -> Optional[AnalysisRecord]: ...
    def list_by_model(self, model_id: str, owner_id: Optional[str] = None) -> List[AnalysisRecord]: ...


@runtime_checkable
class IStressTestRepository(Protocol):
    def create(self, record: StressTestRecord) -> StressTestRecord: ...
    def get_by_id(self, stress_test_id: str, owner_id: Optional[str] = None) -> Optional[StressTestRecord]: ...
    def list_by_model(self, model_id: str, owner_id: Optional[str] = None) -> List[StressTestRecord]: ...


@runtime_checkable
class IFaultTestRepository(Protocol):
    def create(self, record: FaultTestRecord) -> FaultTestRecord: ...
    def get_by_id(self, fault_test_id: str, owner_id: Optional[str] = None) -> Optional[FaultTestRecord]: ...
    def list_by_model(self, model_id: str, owner_id: Optional[str] = None) -> List[FaultTestRecord]: ...


@runtime_checkable
class IFailureMemoryRepository(Protocol):
    def save_or_update(self, record: FailureMemoryRecord) -> FailureMemoryRecord: ...
    def get_by_id(self, memory_id: str, owner_id: Optional[str] = None) -> Optional[FailureMemoryRecord]: ...
    def list_by_model(self, model_id: str, owner_id: Optional[str] = None) -> List[FailureMemoryRecord]: ...


@runtime_checkable
class IPredictionRepository(Protocol):
    def create(self, record: PredictionRecord) -> PredictionRecord: ...
    def get_by_id(self, prediction_id: str, owner_id: Optional[str] = None) -> Optional[PredictionRecord]: ...
    def list_by_model(self, model_id: str, owner_id: Optional[str] = None) -> List[PredictionRecord]: ...


@runtime_checkable
class IWarningRepository(Protocol):
    def create(self, record: WarningRecord) -> WarningRecord: ...
    def get_by_id(self, warning_id: str, owner_id: Optional[str] = None) -> Optional[WarningRecord]: ...
    def list_by_model(self, model_id: str, owner_id: Optional[str] = None) -> List[WarningRecord]: ...
